### ISSUE TITLE
if text is less than setShowingLine(10) then app get crashed

### ISSUE THREAD

**Issue by ManishAndroidIos** [mahimrocky/ShowMoreText#6]
2020-08-18 12:44:23.719 6719-6719/com.app.keypay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.keypay, PID: 6719
    java.lang.StringIndexOutOfBoundsException: String index out of range: -10
        at java.lang.String.substring(String.java:1975)
        at com.skyhope.showmoretextview.ShowMoreTextView$1.onGlobalLayout(ShowMoreTextView.java:126)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2254)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:713)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6533)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by ahsan-idrees-brainx** [comment]
Same issue with me

**Comment by renatosousa-github** [comment]
I solved this problem by adding a string length validity, string.lenth > 10.

**Comment by renatosousa-github** [comment]
I solved this problem by adding a string length validity, string.lenth > 10
